# Generated by Django 4.2.5 on 2023-09-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("to_do_list", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
