# Generated by Django 4.2.5 on 2023-09-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("to_do_list", "0003_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(null=True),
        ),
    ]
